version: '3.8'

services:
  student-portal-ui:
    build:
      context: .
      dockerfile: Dockerfile
    image: sydwellcbu/student_portal_ui:0.0.1-SNAPSHOT
    container_name: student-portal-ui
    ports:
      - "4200:4200"
      - "9113:9113"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  app-network:
    driver: bridge
