version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular-container
    ports:
      - "4200:80"  # Expose Angular's internal port 80 to the host port 4200
    environment:
      BACKEND_API_URL: http://student-portal-container:8080  # Backend service URL for API communication
    networks:
      - student_portal_network  # Connect to the shared network

networks:
  student_portal_network:
    external: true  # Reuse the shared network created in the backend setup
