apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml --namespace student-portal-ns
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: maildev
  name: maildev
  namespace: student-portal-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: maildev
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml --namespace student-portal-ns
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: maildev
    spec:
      containers:
        - image: maildev/maildev
          livenessProbe:
            exec:
              command:
                - nc
                - -z
                - localhost
                - "1025"
            failureThreshold: 3
            periodSeconds: 20
            timeoutSeconds: 5
          name: maildev
          ports:
            - containerPort: 1080
              protocol: TCP
            - containerPort: 1025
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: "268435456"
            requests:
              cpu: 100m
              memory: "134217728"
      restartPolicy: Always
