apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mysql-data
  name: mysql-data
  namespace: student-portal-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
