apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml --namespace student-portal-ns
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: student-portal
  name: student-portal
  namespace: student-portal-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: student-portal
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml --namespace student-portal-ns
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: student-portal
    spec:
      containers:
        - env:
            - name: CLIENT_HOST
            - name: CLIENT_PORT
            - name: SPRING_DATASOURCE_PASSWORD
              value: student_pass
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-db:3306/student_portal
            - name: SPRING_DATASOURCE_USERNAME
              value: student_user
            - name: SPRING_MAIL_HOST
              value: maildev
            - name: SPRING_MAIL_PASSWORD
            - name: SPRING_MAIL_PORT
              value: "1025"
            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
              value: "false"
            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
              value: "false"
            - name: SPRING_MAIL_USERNAME
          image: sydwellcbu/student_portal:0.0.1-SNAPSHOT
          livenessProbe:
            exec:
              command:
                - curl -f http://localhost:8083/api/v1/actuator/health
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
          name: student-portal
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: "1073741824"
            requests:
              cpu: 500m
              memory: "536870912"
      restartPolicy: Always
